### ISSUE TITLE
Setting auth persistence.

### ISSUE THREAD

**Issue by phoenixrip** [prescottprue/react-redux-firebase#339]
Trying to set the auth-state-persistence to 'none' using the method described [here](https://firebase.google.com/docs/auth/web/auth-state-persistence) on the firebase object added by firebaseConnect: but I'm getting:

`Uncaught TypeError: firebase.auth(...).setPersistence is not a function`

(V1.5.1)

It seems it is not possible to set the persistence type of the auth in v1.5.1.
Am I missing something?

Is this because the firebase dependency for react-redux-firebase is 3.9.0 and auth state persistence options were added to firebase later?

Thanks in advance for any help :)

**Comment by prescottprue** [comment]
@phoenixrip You are correct. Have you tried out [using `v2.0.0`](http://docs.react-redux-firebase.com/history/v2.0.0/#use)? It has a more simple API and allows you to pass your own Firebase instance (you can manage version and call `setPersistence` yourself).

Not only does v2.0.0 give you that capability, but it has actually proved to be much more performant in our production applications. We are very close to releasing it as `latest` (my company has switched all of our production applications over to `v2.0.0`), which is the only reason that `v1.5.*` hasn't gotten a ton of love recently.

**Comment by phoenixrip** [comment]
Thanks so much for a quick response.... I will start working on transitioning to v2.0.0 now.

**Comment by phoenixrip** [comment]
Well, that was insanely easy.

Not done by any means, but getVal as a drop in replacement (except having to add .data to paths) makes this a really nice transition.

I gotta say, this is a really beautiful, well written and supported bit of software. Thank you so much for it. Will definitely be contributing once the project goes live :)
