### ISSUE TITLE
feat(query): support FieldPath within query config

### ISSUE THREAD

**Issue by oloflindh** [prescottprue/react-redux-firebase#619]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**
When trying to use FieldPath in a query's where parameters, I get TypeError: where.map is not a function. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox](https://codesandbox.io/) or similar.**
I'm trying to run a query on a collection, with emails in the query path. I want to get docs where "users.[email_address].role" == some role. The way I've been doing this is by using FieldPath to create a path, like this:

`var rolePath = new firebase.firestore.FieldPath('users', someEmail, 'role')
collection.where(rolePath, '==', someRole).get()`

It works fine on its own, but when I try to do this with firestoreConnect, things break and I get a "TypeError: where.map is not a function". Is FieldPath simply not supported in firestoreConnect queries?

```
firestoreConnect(props => {
    const rolePath = new firebase.firestore.FieldPath('users', props.userEmail, 'role')

    return [
      {
        collection: 'projects',
        where: [rolePath, '==', props.userRole]
      }
    ]
})
```

**Which versions of dependencies, and which browser and OS are affected by this issue? Did this work in previous versions or setups?**

I've never been able to get this to work, neither in the current version of react-redux-firebase or versions prior. Running Chrome.

**Comment by prescottprue** [comment]
Yeah, never really tried using a FieldPath as part of the query. When doing this I usually just grab the value of the path like:

```js
firestoreConnect(props => {
    const rolePath = new firebase.firestore.FieldPath('users', props.userEmail, 'role')

    return [
      {
        collection: 'projects',
        where: [`users.${props.userEmail}.role`, '==', props.userRole]
      }
    ]
})
```

That said, we should definitely support FieldValue in queries.

**Comment by oloflindh** [comment]
@prescottprue Yeah that's is what I normally would have done. But I think the fact that it's an email complicates things. If I'm not mistaken your solution would have worked fine for a uid, but the '.' of an email address messes with the doc path, which is why I tried to use FieldPath in the first place.

**Comment by prescottprue** [comment]
@oloflindh I wonder if you put a `\` in front of the `.` in the email if that would fix things? Either way, would definitely like to support this.

**Comment by prescottprue** [comment]
Support released in [v0.9.0](https://github.com/prescottprue/redux-firestore/releases/tag/v0.9.0). Reach out if it doesn't work as expected. Thanks for reporting!
